# Generated by Django 4.1.3 on 2022-11-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=255)),
                ('segundo_nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
